### ISSUE TITLE
Proposal : MTU option for overlay driver ?

### ISSUE THREAD

**Issue by eesprit** [docker/libnetwork#1021]
The overlay driver has a static definition to deal with overhead and MTU.
That works on standard networks, but if the physical network already needs to have a lower MTU, things gets broken.
For exemple, when using Openstack (which can used VXLAN, or other mecanisms that needs to lower the MTU) to deploy multiple docker hosts, the MTU is already lowered to 1450 at the host level : overlay networks won't work on it, because they also defines a 1450 MTU.

Of course, there are project to reuse the Neutron Stack in Docker, or other drivers to have multi-hosts networking, but IMHO having the "native" one working in such environments would be better.

The bridge networks already allow to (re)define the MTU, it could even be defined as a daemon option, and it works nicely. But the overlay network driver does not allow that, neither to define the MTU at the daemon scope.

It would be nice for such cases to be able to define the MTU when creating the overlay network, or perhaps reuse the daemon defined one to compute the good value, or to guess it from the interface used for VXLAN ? Not sure what the best approch would be.

If I am missing something or if there is another way to work around that, feel free to mention it.

Regards.

**Comment by mavenugo** [comment]
@eesprit we had a recent discussion around this and we thought it would be best to introduce the `--mtu` flag in `docker network create` and let the user specify the mtu depending on the infrastructure they run on. This is inline with your proposal i think. Are you willing to push a PR to take care of this ?

**Comment by adrecord** [comment]
I tried running a modified dockerd with [vxlanVethMTU](https://github.com/docker/libnetwork/blob/335f49fc9582659c60369235b905617a47569490/drivers/overlay/overlay.go#L28) set to 8950, to see if that would allow support for jumbo frames between containers on separate hosts connected to a swarm overlay network.

As expected, that does successfully cause the eth0 interface (connected to the multi-host overlay) inside the containers to have an MTU of 8950, so that's good.  The corresponding veth device on the docker host machines still had an MTU of 1500, so I had to manually change those (ip link set dev vethxxxx mtu 8950).  With that done on both docker hosts, I was hopeful that jumbo frames would work between the two containers.

Unfortunately, tracepath shows that the MTU is cut down by the swarm network gateway.  For example, if I create the overlay network on subnet 196.168.1.0/24 and the containers are given IP addresses 192.168.1.3 and 192.168.1.4, tracepath shows that the MTU is 8950 when leaving the docker container, but when it gets to 192.168.1.1 (the overlay gateway), that the MTU is reduced to 1500.

All MTUs on the docker hosts are set appropriately and so is eth0, connected to the overlay network, inside the container.  eth1 in the containers is still set to 1500, but that's the host-only 172.x network, which I don't think is in play here.

@mavenugo could you give me some direction of what else would need changing to allow the gateway of the overlay network (in swarm mode) to support the larger MTU size?

Thanks.

**Comment by aboch** [comment]
@adrecord
First you need to change overlay driver code to honor the [mtu driver option](https://github.com/docker/libnetwork/blob/v0.8.0-dev.2/netlabel/labels.go#L34) , so that the it will set the requested mtu when creating the veth pair on both the sides.

For the docker gateway network, what could be done is to document that user needs to manually create the default gateway network before creating any overlay network to be able to set its MTU to the jumbo size.

```
docker network create --opt com.docker.network.bridge.name=docker_gwbridge --opt com.docker.network.bridge.enable_icc=false --opt com.docker.network.bridge.enable_ip_masquerade=true --opt com.docker.network.driver.mtu=<...> docker_gwbridge
```

If instead we also want this to be done automatically, it is not clear how libnetwork would choose the MTU value when it creates the docker gateway bridge network. Maybe from the daemon level mtu ?

**Comment by aboch** [comment]
@adrecord 
It turned out we needed this feature sooner than we thought, we need it for docker 1.12.
I know you were looking into this, but today I was asked to add the funtionality ASAP and I pushed #1349, sorry for that.

**Comment by adrecord** [comment]
@aboch No worries.. I hadn't gotten back to working on this yet.  I'm glad that you were able to get it done and in time for 1.12.  Thanks.  :)

**Comment by bklau** [comment]
@mavenugo : 2 questions:

1. What version of Docker is this fix in?
2. Does this fix applied to just the "bridge" driver or to the "overlay" driver as well? The Docker documentation seems to indicate the "bridge" driver only. Please clarify. I'm a bit lost.

thx.

**Comment by aboch** [comment]
@bklau 

> What version of Docker is this fix in?

starting from docker 1.12.0

> Does this fix applied to just the "bridge" driver or to the "overlay" driver as well?

"bridge" mtu was already configurable. This change allows to do the same for overlay networks.

**Comment by bklau** [comment]
@aboch : Thx. Better documentation needed, I guess :)

**Comment by eugenepark1** [comment]
what about for "macvlan" driver? I cant seem to configure mtu by setting -o com.docker.network.driver.mtu=1450
