### ISSUE TITLE
Proposal: IPAM Driver RequestAddress Add an option to know which operation from libnetwork

### ISSUE THREAD

**Issue by godliness** [docker/libnetwork#1057]
I wrote a ipam driver by myself, and i need manage an ip pool in etcd database, when we run "docker stop" and "docker rm", libnetwork will call the ReleaseAddress interface, i have a requirement which is when we run "docker stop" we do not need release ip from the pool but "docker rm" need release ip from the pool,  so could we add option to let ipam driver know which operation the docker daemon does.

**Comment by raghakk** [comment]
**Analysis of your Requirement:**
DockerEngine does not maintain seperate state for cmds 

1. **docker stop containerID** 
2. **docker rm -f containerID**

 Hence giving a context in the current design may be tough is my opinion . 
 Once the stop or ContainerRemove cmd(command) is received...stateExit would be hit and in stateExit..."daemon.Cleanup" function is invoked which releases all resources used by the container.

As an alternative and by concept of CNM model of libnetwork...i checked...if by doing "docker network disconnect network containerID"...then on invoking "docker stop conatinerID" will u r requirement be handled...**Even that does not work**. Because disconnect also result in cleaning up of the endpoint....basically calling ep.Leave and ep.Delete...
May be DockerTeam has now supported, pass the IP as argument to the container.. network disconnect should result in endpoint cleanup....which is ok.

**Alternative Solution, If i have understood your requirement:**
when start container you can specify the required IP. This will ensure ur container is started with the required IP.
>sudo docker run -d --net=n0 --name=c0 **--ip=172.20.55.66** busybox top

**If DockerTeam provides some explanation of the design rationale...it would be of great help.**

**Comment by godliness** [comment]
Thanks, unless we change the docker code that we could finish this feature, now i just use --ip to avoid this problem. Looks like you are working on docker also, do you have qq? we could talk about this in advance. my qq is 369101940
