### ISSUE TITLE
libnetwork _really_ _really_ _really_ slow on startup in some cases

### ISSUE THREAD

**Issue by cpuguy83** [docker/libnetwork#1171]
When starting up docker, if `--cluster-store` is set to an IP address that belongs to a container, and that container is not using `--net=host`, initializing libnetwork takes a VERY VERY (VERY x10) long time.

Example:

```
$ docker daemon -D
...
$ docker network create --subnet 192.168.250.0/24 test
$ docker run -d --name etcd --ip 192.168.250.2 --restart=always quay.io/coreos/etcd --listen-client-urls http://192.168.250.2:2379 --advertise-client-urls http://192.168.250.2:2379
$ kill $(pidof dockerd)
$ docker daemon -D --cluster-advertise 127.0.0.1:2375 --cluster-store etcd://192.168.250.2:2379
```

The last line takes a couple of minutes.
Meanwhile if I use `--net=host` and 127.0.0.1 for the etcd url it's as fast as it normally is.

**Comment by mavenugo** [comment]
@cpuguy83 I think we should document this scenario and recommend not to use such configurations.
That is especially true because, one should NOT assume direct container reachability through its ip-address from the host networking stack. It will vary between network drivers. For example, host cannot reach the containers running in networks created using Overlay or Vlan drivers.

Can you please confirm if the bootup time improves if the kv container is run with port-mapping and the `--cluster-advertise` is configured to access the localhost or via host-ip (and mapped-port) ?

**Comment by cpuguy83** [comment]
I think we can close this. WHile it is a problem, it is marginalized by swarm-mode.
