### ISSUE TITLE
Overlay network lost packet occasionally even connect to container in same host 

### ISSUE THREAD

**Issue by mimousewu** [docker/libnetwork#1402]
I was deploying docker daemon v1.11.2 and swarm 1.2.4-rc2 to our production environment. I have only 2 nodes, 1 of them is the swarm master itself. but in some reasons, sometimes, the network lost packets while try to ping from one container to other. It mostly happened in days later.
Now, I have to expose all ports outside and use host ip address and exposed ports to combine our services. Thank god, it works fine. But I still want to get this fixed.
![overlay_fail](https://cloud.githubusercontent.com/assets/7788283/17760740/a6ad8c84-6534-11e6-9286-18c981b009af.jpg)

**Comment by bmitch3020** [comment]
I've experienced this issue in a Docker 1.12.x environment, running on RHEL 7.3, kernel 3.10.0-514, and an overlay network setup with consul (swarm mode was not enabled, but the old container based swarm was used with this).  It was always right around 7 pings we would lose so there appears to be a 7 second timeout somewhere. It happened when pinging the IP and it happened even with the target container was on the same host, so I don't believe it was related to DNS or physical network issues. Consul itself was very responsive too. If we waited 15-30 minutes, the problem would happen again for the same IP.

We've since upgraded to 1.13-rc7 and replaced consul with swarm mode. With this new configuration the problem no longer occurs.
