### ISSUE TITLE
Libnetwork ignores RequestPool responses by plugins if a host interface is already connected to the same subnet

### ISSUE THREAD

**Issue by ofiliz** [docker/libnetwork#1465]
I am hitting a problem (seems to be a behavior change from 1.11 to 1.12) that broke my IPAM plugin:

1) When creating a new network, libnetwork sends a RequestPool request, as expected.
2) IPAM plugin returns a valid subnet in the PoolID field in RequestPool response.
3) Libnetwork ignores the response and sends the exact RequestPool request from step1 again. This causes an infinite loop between steps 2-3.

I ran a few experiments. It seems the reason libnetwork ignores the subnet in response in step3 is that one of the host network interfaces has an IP address in that subnet. This looks like a bug. Having a host interface connected to the same subnet is a perfectly valid case: Containers can be on the same IP subnet as the host.

Is the current 1.12 behavior intentional? Or is it just a bug?

**Comment by aboch** [comment]
#1095 moved the overlap check into libnetwork core. It looks like it introduced this issue, where the remote ipam driver is asked again and again for a new pool until it returns one which does not conflict with any route on the host.
This only works under the assumption the ipam driver will return a new pool, and that it eventually runs out of predefined pools.

**Comment by ofiliz** [comment]
Looking at the code, it seems this check (in (n *network) requestPoolHelper) is being enforced for local scope networks only. Global scope networks are allowed to bypass and hence share the same subnet as their host (which by itself seems like a bug since the RequestPool request's AddressPool was the _local_ default address pool).

My understanding is that global scope networks require Swarm. In that case, this behavior effectively blocks containers from sharing the same subnet as their host everywhere except Swarm.

@mrjana @mavenugo, if you can describe what the intent is, I can make the necessary fix and send a PR. But let's first agree on what the correct behavior is here.

**Comment by aboch** [comment]
@ofiliz 

The intent is that when libnetwork is left in charge of selecting an address pool - in other words when the user does not specify the `--subnet` option - for a local scope driver network, it will request IPAM driver for a new pool until one which does not overlap with any local route or nameserver address is returned.

As you said, libnetwork does not care to run the same check for global scope networks (networks which span multiple hosts), because the idea is that if a subnet can be deemed a priori good across multiple hosts, then it is because the network driver can assure the interfaces are isolated from the host interfaces (like in the overlay driver case on linux where the overlay bridge lives in a separate network namespace).

Please note that when the `--subnet` is explicitly specified, libnetwork respects it, it will not run any overlap check, regardless of the network scope.

**Comment by aboch** [comment]
Also, from the IPAM driver point of view, each pool request is to be treated as an independent event.

The IPAM driver must not return the same address pool to two independent pool requests (unless the pool requests are for the same explicit pool).

This is the basic requirement for docker to support multiple networks with automatic pool assignement.

**Comment by ofiliz** [comment]
@aboch "for global scope networks ... the idea is that if a subnet can be deemed a priori good across multiple hosts, then it is because the network driver can assure the interfaces are isolated from the host interfaces"

Yes, agreed. But as I said above, my understanding is that global scope networks are only supported for Swarm today. If this is true, libnetwork's current behavior effectively blocks containers from sharing the same subnet as their host outside of Swarm mode.

So if I don't use Swarm, I have to use local-scope plugin, and the only option is to manually pass --subnet flag. There is no way for an IPAM plugin to automatically assign a subnet. This might be okay, but isn't as convenient.

Yes, the IPAM driver returning the same pool was my bug, fixed.

**Comment by aboch** [comment]
Just a clarfication: Gobal scope networks were supported since 1.8.x (overlay networks) with the daemon relaying on  a remote datastore (`--cluster-store` and `--cluster-advertise` daemon options).

Regarding
> [...] libnetwork's current behavior effectively blocks containers from sharing the same subnet as their host outside of Swarm mode

This is only partially true.
As I said, if the network is created with an explicit subnet, libnetwork does not run any overlap check:

```
$ sudo ip address show wlp2s0 | grep 192
    inet 192.168.100.126/24 brd 192.168.100.255 scope global dynamic wlp2s0
$ 
$ docker network create --subnet 192.168.100.0/24 nw
d08b8ec8925128fee384f80e03df886e2b883349e079ff63f11c653a9833e555
$ 
$ sudo ip address  | grep 192
    inet 192.168.100.126/24 brd 192.168.100.255 scope global dynamic wlp2s0
    inet 192.168.100.1/24 scope global br-d08b8ec89251
$ 
```

**Comment by mavenugo** [comment]
@aboch @ofiliz if there is a difference in behavior for user specified `--subnet` and system (plugin)-chosen subnet, then that must be considered as a bug. It seems like in this case, we do treat the user specified --subnet as special and allow overlapping addresses while the plugin chosen one is rejected. I think we should fix that.

**Comment by mrjana** [comment]
@ofiliz A basic question:

> Having a host interface connected to the same subnet is a perfectly valid case: Containers can be on the same IP subnet as the host.

So when you try to reach the container IP from the host and the host and the container is sharing the same subnet which route does it take? Or are you suggesting a scenario very similar to docker0 where the container and docker0 belongs to the same subnet. If it is the latter,  then the we need to follow the same solution as we do for docker0. Since docker0 already exists and the subnet is known based on docker0's IP we create the default bridge network using the `--subnet` option which is what needs to happen here. Am I missing something obvious here?

**Comment by mrjana** [comment]
@mavenugo In our design we consider IPAM plugin/driver to be pretty much platform independent and should not concern itself with host specific assumptions. In effect this makes the plugin/driver to sit anywhere not just in this host. It is the job of libnetwork to resolve any conflicts that happen with the host. But may be there is an avenue to improve the protocol between libnetwork and IPAM plugin to clearly say why it doesn't like this subnet. So if it can somehow say that this subnet is not usable in this host then IPAM can try providing a different auto-subnet.

**Comment by ofiliz** [comment]
@mrjana 
> when you try to reach the container IP from the host and the host and the container is sharing the same subnet which route does it take?

An example configuration could be a bridge/switch in L2 mode: The host has an eth0 and a bridge0. Eth0 is added as a slave to bridge0. The host IP address is assigned to bridge0. When you ping the container's IP address, the frame is broadcast (assuming no MAC learning) to all interfaces connected to the bridge, including eth0 and any veths for containers. In other words, all interfaces are in the same L3 routing domain.

**Comment by mrjana** [comment]
Yes, in that case it is just a variant of `docker0` which can also be setup that way. In these kinds of cases where we are trying to define the network based on the host networking state, the creation of the network needs to happen based on the subnet to which that underlying bridge belongs to. IPAM should never be involved in making that decision. It should come from user or some other higher level machine management or other orchestration systems when the network is created.

**Comment by mchiappero** [comment]
@aboch @mrjana I've been bitten by this bug too and I think there should be a flag to override this check at the very least.
Now, two major problems I see:
1. Many of the assumptions here listed are not mentioned in the IPAM driver specification, which in turn means this behaviour is bug.
2. The bridge use case mentioned above is a valid one (well, the one I'm working on involves the use of IPVLAN instead of a bridge and a few other things, but it's the same problem), so it must be supported without the need for the --subnet flag, or people will most likely not use the plugin at all.

> [the decision] should come from user or some other higher level machine management or other orchestration systems when the network is created

so what if my orchestration system is (also) the IPAM driver and knows perfectly which pool is right?

**Comment by mchiappero** [comment]
> Also, from the IPAM driver point of view, each pool request is to be treated as an independent event.
> 
> The IPAM driver must not return the same address pool to two independent pool requests (unless the pool requests are for the same explicit pool).

Also this makes hard to comply to the specs, as the driver needs to keep track of previously returned pools (what if the driver crashes?).

**Comment by aboch** [comment]
@mchiappero 

> as the driver needs to keep track of previously returned pools

Yes, the driver needs to keep a reference count of the already assigned pools.
Also because user can create multiple networks all explicitly using the same address pool.
The `ReleasePool()` requests originating on network deletion must effectively release the pool only when the reference count is zero.

Going back to the specific subject of independent pool requests, I feel it is covered in #489 by:
> In case the subnet is not passed, its upto the ipam driver implementation to handle the case appropriately. The default/in-built IPAM driver will return the first un-allocated subnet
