### ISSUE TITLE
Create an IPVS service with Flags=1, but return Flags==3

### ISSUE THREAD

**Issue by m1093782566** [docker/libnetwork#1921]
Create an IPVS service with Flags=1, see,

```
s := Service{
	AddressFamily: nl.FAMILY_V4,
	SchedName:     "rr",
        Protocol: syscall.IPPROTO_TCP,
	Port: 80,
        Address: net.ParseIP("1.2.3.4"),
	Netmask: 0xFFFFFFFF,
        Flags: 1,
}

ipvs.NewService(&s)
got := ipvs.GetService(&s)
```

It turns out that **got.Flags == 3** !!

I wonder why?

**Comment by m1093782566** [comment]
@mrjana @mavenugo @dhilipkumars @allencloud Any thoughts?

**Comment by mavenugo** [comment]
@m1093782566 I guess that's because of the way the ipvs core is implemented. 
Every service is hashed into the service table and hence flag (`IP_VS_SVC_F_HASHED     0x0002`) is set for every service. You can experiment by NOT setting any flag and the returned Flag will be 2. Also you can try with other flags such as `flag-1` (0x8) and you will see the return value as 0xA.

This should not ideally impact your Persistence needs (or for that matter, should not ideally impact anything). You can ignore it by simply masking 0x2.

**Comment by m1093782566** [comment]
Yes, that's true.
