### ISSUE TITLE
Docker Custom(User-Defined) Network not working after restart docker

### ISSUE THREAD

**Issue by MSaadatt** [docker/libnetwork#1943]
Hello,
I have created a user-defined network called network00 after that I use ifconfig command to show network interfaces. network00 is showing in the interfaces. but.... .

After I restart docker service or ubuntu machine my custom network not showing in ifconfig interfaces but when I using:

$ docker network ls

showing network00 and other default networks in docker.

my container can't connet to this network and say cannot find network00(0abc586...........)!!!! but network is present in network ls

How Can I Sovle it?!!!!
Docker version:::
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:11 2017
 OS/Arch:      linux/amd64
 Experimental: false

Docker info:::
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 9
Server Version: 17.06.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 94
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-96-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 31.41GiB
Name: yomo
ID: JYTH:3WNI:ZRHM:MC5N:EMYZ:EWCH:FLTN:4ONZ:X7XE:VI72:2LO2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
WARNING: No swap limit support

**Comment by luccasmenezes** [comment]
I had the same problem on some production systems. Had to go back to kernel 4.4.0-93. Still don't know what caused.

**Comment by MSaadatt** [comment]
Thanks @luccasmenezes for your suggestion, But I'm looking for better solution.
Is that a bug in docker?

**Comment by luccasmenezes** [comment]
@MSaadatt Yeah me too, I reverted the kernel just as a temporary solution. Still don't know what is cause.

**Comment by MSaadatt** [comment]
@thaJeztah Can you solve my problem?
Is that a bug on docker?

**Comment by thaJeztah** [comment]
If the issue is resolved after downgrading the kernel from 4.4.0-96 to 4.4.0-93, then this sounds like a kernel bug (in this case, an issue with the Ubuntu kernel, or a patch that was back ported by them).

I suggest;

- to write down the _exact_ steps to reproduce (`docker network create ...` with all the options you're using etc)
- try running the check-config.sh script to see if anything stands out (you can find that in the `contrib` directory of the Moby repository: https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh)
- temporarily start the daemon in debug mode; this will print more detailed information in the daemon logs;

  - create a `/etc/docker/daemon.json` configuration file (if you don't have one yet)
  - add the `"debug":true` option; it's JSON so if this is the only option you're using, the file should look something like: `{"debug":true}`)
  - reload the daemon configuration (`sudo systemctl reload docker`)
  - check if the daemon and system logs give any useful information


If you suspect there's a bug in the kernel, you can report those here: https://bugs.launchpad.net/ubuntu/+source/linux/+filebug


I just tried reproducing, but the machines in my environment are still running 4.4.0-93. I'm using DigitalOcean for my testing, and it looks like they don't have 4.4.0-96 available yet

**Comment by MSaadatt** [comment]
@thaJeztah Thanks for your reply.
Can you test it later on your DigitalOcean after 4.4.0-96 kernel available on your Droplet and report it in this issue?
Thanks

**Comment by thaJeztah** [comment]
will do when it arrives there :smile:

**Comment by MSaadatt** [comment]
This issue has been fixed in docker versoin 17.09 and ubuntu kernel 4.4.0-97-generic.
Thanks for cooperation :)
@luccasmenezes
@thaJeztah

**Comment by MSaadatt** [comment]
This issue have not resolve yet, using 4.4.0-97 kernel and docker 17.09

**Comment by MSaadatt** [comment]
Resolved :)
