### ISSUE TITLE
bridge network is assigned gateway ip address

### ISSUE THREAD

**Issue by donnib** [docker/libnetwork#2061]
Hi, 

doing this : 
`
docker network create --subnet 10.100.50.0/22 --gateway 10.100.48.1 iptastic`

will create bridge network with the worst ip assigned.....the gateway ip. That should happen. I believe this is a bug.

**Comment by donnib** [comment]
Ok this seems not to be a bug, it's just a wrong way i am using it.

**Comment by selansen** [comment]
what docker CE version are you using ?
Let me try it locally on my setup.

**Comment by selansen** [comment]
I tried same command on 17.11 CE and network does not uses gateway IP.

docker@ELANGO-CE-EDGE-ubuntu-2:~$ docker network create --subnet 10.100.50.0/22 --gateway 10.100.48.1 iptastic
3727512a30596b5a12e5ab5399583a370c2e6b4dfc9f39abe8ade27eeb3274d7

Usage:  docker network inspect [OPTIONS] NETWORK [NETWORK...] [flags]

Display detailed information on one or more networks
docker@ELANGO-CE-EDGE-ubuntu-2:~$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
badce8f23baa        bridge              bridge              local
02400f325fa5        docker_gwbridge     bridge              local
790b63cc1980        host                host                local
0tqhl96cuwoc        ingress             overlay             swarm
3727512a3059        iptastic            bridge              local
ca355b76083a        none                null                local
docker@ELANGO-CE-EDGE-ubuntu-2:~$ docker network inspect iptastic
[
    {
        "Name": "iptastic",
        "Id": "3727512a30596b5a12e5ab5399583a370c2e6b4dfc9f39abe8ade27eeb3274d7",
        "Created": "2018-01-22T12:17:36.171995099-08:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "10.100.50.0/22",
                    "Gateway": "10.100.48.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]
docker@ELANGO-CE-EDGE-ubuntu-2:~$ docker version
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:37:39 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:36:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
docker@ELANGO-CE-EDGE-ubuntu-2:~$

**Comment by donnib** [comment]
I am using Docker version 17.12.0-ce, build c97c6d6

After the network is created i do a ip addr and the bridge network created has inet equal to the gateway i specified.

**Comment by selansen** [comment]
Can you pls post  "docker network <network-name> inspect" output and "ip a" ?

Let me try 17.12

**Comment by selansen** [comment]
I did more digging into this and realized there is a misunderstanding in your understanding of bride network.  
when you give --gateway (or we use default IP in the subnet range) , we create   interface that will northbound traffic egressing the bridge . you should use --gateway as the nexthop which is what you have given in your CLLI command. to see the actual bridge info, pls use brctl commands. ip all will list all the interfaces getting created for that bridge. in your CLI command the given  subnet is 10.100.50.0/22.
If you see below what is network and first min IP address , this will give you fair idea about why we use the first IP as default gateway.  Hope this clarifies. Pls close this issue.
ipcalc 10.100.50.0/22
Address:   10.100.50.0          00001010.01100100.001100 10.00000000
Netmask:   255.255.252.0 = 22   11111111.11111111.111111 00.00000000
Wildcard:  0.0.3.255            00000000.00000000.000000 11.11111111
=>
Network:   10.100.48.0/22       00001010.01100100.001100 00.00000000
HostMin:   10.100.48.1          00001010.01100100.001100 00.00000001
HostMax:   10.100.51.254        00001010.01100100.001100 11.11111110
Broadcast: 10.100.51.255        00001010.01100100.001100 11.11111111
Hosts/Net: 1022                  Class A, Private Internet

**Comment by fcrisciani** [comment]
@donnib also here(https://docs.docker.com/engine/reference/commandline/network_create/#usage) you can find the additional information about the network create flags. Closing this one for now, but feel free to follow up if you have other questions

**Comment by donnib** [comment]
So @fcrisciani and @selansen how would i create a bridge network without an gateway ip and subnet ? What i want is a bridge network of eth0 which then i can use in the containers where i hand out static public ip address which is in the same subnet as the ip eth0 (host net) has ?

**Comment by selansen** [comment]
https://docs.docker.com/engine/userguide/networking/get-started-macvlan/

**Comment by gsomlo** [comment]
I'm also wondering if there's a good way to prevent setting up the gateway IP address (or any other IP address, for that matter) on the bridge interface? I like the ability to configure an IP address, subnet, and default gateway on a container, but I'd like to avoid relinguishing ownership of the gateway IP itself to Docker. For instance, assume this setup before/outside of Docker:
```
# ifconfig br0
br0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
     inet 192.168.10.75  netmask 255.255.255.0  broadcast 192.168.10.255

# route -n
Destination   Gateway       Genmask        ...  Use Iface
0.0.0.0       192.168.10.1  0.0.0.0        ...    br0
192.168.10.0  0.0.0.0       255.255.255.0  ...    br0

# brctl show
bridge name   bridge id   STP enabled   interfaces
br0           XXXXXXXXX   no            eth0
                                        tap0
                                        ...
```
IOW, I have an existing bridge, with an already configured IP, and a LAN with an existing subnet and an existing default gateway. If I wanted to set up docker containers capable of fully participating on that LAN segment, including the ability to communicate with the host, I'd like to do the following:
```
  docker network create \
    --subnet 192.168.10.0/24 \
    --ip-range 192.168.10.192/26 \
    --gateway 192.168.10.1 \
    -o com.docker.network.bridge.name=br0 \
    docker42
```
At this point, Docker clobbers br0's IP address (.75) and replaces it with that of the gateway (.1). I can manually fix that (but shouldn't have to)...:
```
ip addr del 192.168.10.1/24 dev br0
killall dhclient
dhclient br0
```
... in order to restore br0's proper address, before bringing up a container like so:
```
docker run -d --network docker42 --ip 192.168.10.195 nginx
```
At this  point, I can connect to my container from everywhere on the LAN, including my host, and from anywhere else my LAN is reachable (e.g. via routing hops, subject to firewall rules, etc.), which is the desired result. The only obstacle is Docker's insistence on "owning" the default gateway. I want the gateway to be used as part of the IPAM setup, but please-please help me figure out how to avoid having it applied to the bridge interface itself, where it doesn't belong!!!!

Even if you're going to tell me that using a pre-existing bridge (e.g. br0) is not supported, I'd still like to
```
  docker network create \
    --subnet 192.168.10.0/24 \
    --ip-range 192.168.10.192/26 \
    --gateway 192.168.10.1 \
    -o com.docker.network.bridge.name=br42 \
    docker42
```
**without** setting the IP of br42 to **anything** (so I can figure out how to wire it into my pre-existing LAN segment with a pre-existing gateway device, etc).

Is there an option to "docker network create" that would accomplish this (i.e., use the gateway address in IPAM, but don't set it on the bridge interface)? If not, does anyone know of a current proposed patch or pull request implementing such an option that I could study? If not, would such a patch be of interest? Lastly, to anyone recommending macvtap: I only ever saw examples of it being configured with a parent set to the physical host network interface, and with the caveat that host<->container communication won't work. Trying to set "-o parent" to a virtual interface, then attempting to connect that virtual interface to an existing bridge didn't work for me, and I couldn't find any documentation anywhere on the internet beyond the basic "slave it to the host physical NIC" or "set it up as a VLAN subinterface", so any links to a more complete macvlan documentation would also be much appreciated!

**Comment by gsomlo** [comment]
oh nevermind, macvlan was the answer after all -- I was mistakenly using "--internal" which, apparently, results in the specified parent being ignored in favor of a dummy parent interface created on-the-fly. Sorry for the noise :)
