### ISSUE TITLE
Provide top-level IP label to allow static assignment of IP to a container

### ISSUE THREAD

**Issue by dave-tucker** [docker/libnetwork#391]

**Comment by mavenugo** [comment]
This was discussed as part of https://github.com/docker/docker/pull/13476 and finally closed due to the reason specified by @icecrime @shykes https://github.com/docker/docker/pull/13476#issuecomment-109363464.

In order to support this requirement, we might have to go with hard-coded flag such as --ip & --ipv6 ?

**Comment by dave-tucker** [comment]
Ok, closing in favour of https://github.com/docker/libnetwork/issues/161
