### ISSUE TITLE
Replace libcontainer network code with libnetwork

### ISSUE THREAD

**Issue by crosbymichael** [docker/libnetwork#41]
Currently libcontainer creates and sets up the interfaces inside the container in the execution work flow.

It would be nice to replace the code located https://github.com/docker/libcontainer/blob/master/network_linux.go with libnetwork.

**Comment by squaremo** [comment]
@crosbymichael Would you give a little more detail for how you see this being arranged? For instance, which responsibilities belong to which libraries.

My (superficial) reading of how libcontainer is used now is that it's given the network configuration, essentially a bridge name and an IP address; then sets up a veth pair, moves one interface into the container namespace and assigns it the IP address.

Presently it looks like libnetwork will deal only with interfaces and IP addresses, presumably with the idea that a driver will create whatever it likes, and only needs libcontainer to move the interface (or interfaces) into the network namespace, and assign the IP(s), at the correct time. So this would need a bit of work to add to libcontainer a "network strategy" that does just that.

However I think this issue is suggesting that those network strategies are moved into libnetwork. In which case, it would need some way of telling libcontainer what they are. Is that more or less the idea?

**Comment by tomwilkie** [comment]
@crosbymichael For a concrete example, I think this is the minimal change that would be needed in libcontainer to support libnetwork:  https://github.com/docker/libcontainer/compare/master...tomwilkie:existing_strategy

Is this something you'd like me to submit as a PR?

**Comment by mrjana** [comment]
@squaremo @tomwilkie When libnetwork is completely integrated with libcontainer, libnetwork will take the entire responsibility of managing the network namespace along with all the network resources contained in it.libcontainer will then make use of the network namespace created and managed by libnetwork to form the container execution environment along with other namespace setups and launching the entrypoint inside the container. You will see a PR to libcontainer related to this in near future

**Comment by squaremo** [comment]
Does an interface in a process's namespace get destroyed when the process exits? That would be a problem if (as it stands now) the driver is asked only on endpoint creation to supply an interface, libcontainer moves it into the namespace, then the container it belongs to is restarted. I admit my understanding here is patchy so perhaps I'm missing a trick.

**Comment by mrjana** [comment]
@squaremo The process namespace a.k.a the sandbox does not get destroyed when the process exits. In fact the namespace will get created by `libnetwork/sandbox` and all the network resources in `sandbox.Info` are moved into it much before the container process is even started. Then when the container process starts libcontainer will make sure that the target process sets into this namespace. 

If the process exits/dies/restarted subsequently the namespace does not go away because it has been decoupled from the process itself. This trick is achieved when we first create the namespace in `sandbox/namespace_linux.go` we in fact create the namespace in the calling process context(in this case the docker daemon) but then immediately bind mount the `/proc` entry to a location which doesn't go away when the process exits. From then on the namespace just lives there until we unmount and remove the path(which we do when the container is removed)

This follows the same design principle of `ip netns add <ns>`. This command creates a netns for you which is present until you destroy it irrespective of which process attaches to it.

**Comment by squaremo** [comment]
Got it, thanks @mrjana.

**Comment by mrjana** [comment]
Closing this since all of this is now taken care of by libnetwork.
