### ISSUE TITLE
Remote plugin can't query for relevant resources during callback

### ISSUE THREAD

**Issue by rlane** [docker/libnetwork#414]
My remote networking plugin needs more information about the network/service/containers than just the ID, so it calls back into the Docker API. This works fine for most callbacks and resources but fails in a few instances:
1. /container/<id> (where id is from services/<EndpointID>/backends) fails during the JoinNetwork callback with a timeout (deadlock?).
2. /networks/<NetworkID> fails during the CreateNetwork and DeleteNetwork callbacks with a 404.
3. /services/<EndpointID> fails during the DeleteEndpoint callback with a 404.

Minimal plugin with the issue: https://gist.github.com/rlane/ff31b506399b915d9543

**Comment by tfukushima** [comment]
Hi, I'm working on [Kuryr](https://github.com/openstack/kuryr), a libnetwork remote driver bridges between Docker and OpenStack Neutron. I'm also looking for ways to retrieve some more information more than what are passed to the remote driver during libnetwork's API calls because currently I'm using `NetworkID` as names of networks in Neutron, which are not user-friendly so much. For now the creation of the resources is the only timing we can retrieve information relate to the network resources because there's no update APIs for the remote drivers.

So I'd like to have access to some more information, say a name of a network to be created, during `/NetworkDriver.CreateNetwork` for instance. There're two ways to achieve this:

1. Allow the remote drivers to get information from the Docker side during the calls to the remote drivers
2. Pass more information as a part of the requests against the remote drivers

I'm Ok with both cases and let me know if I could work on something needed to achieve any of the above solutions. I heard some discussion are going on and I just wanted to catch up with the current states or agreements to avoid unnecessary pull requests not to be merged.
