### ISSUE TITLE
Re. binding overlay driver to an interface

### ISSUE THREAD

**Issue by rhim** [docker/libnetwork#533]
Folks,
Serf requires binding to a specific interface, which is specified with label such as com.docker.network.driver.overlay.bind_interface=eth0. This in turn
requires knowing the correct interface. Since interface names change among different distros, so should this config parameter. Short of adapting the docker install script for the purpose, is there any way we can handle this in the overlay driver itself? How about binding to all non link local addresses?

Thanks,
Himanshu

**Comment by mavenugo** [comment]
ping @mrjana

**Comment by rhim** [comment]
@mrjana - could you please respond? 

Thx.

**Comment by mavenugo** [comment]
@rhim we have a prototype in the works that removes the overlay driver labels `com.docker.network.driver.overlay.bind_interface` and `com.docker.network.driver.overlay.neighbor_ip` and replace them with native docker discovery (https://github.com/docker/docker/pull/16229).

With native docker discovery in place, libnetwork will learn the bind_address instead of bind_interface.
But, the user will be configuring the --bind-address in docker instead of the interface. Will that work for you ?

**Comment by rhim** [comment]
Yes, that should work.

**Comment by fcrisciani** [comment]
looks like the patch mentioned got merged, closing
