### ISSUE TITLE
Removing containers doesn't remove entries in overlay network.

### ISSUE THREAD

**Issue by pawskow** [docker/libnetwork#573]
I use Docker Swarm + Multi-Host Overlay Driver (with consul KV store) + Docker Compose. 
Sometimes, after killing and removing containers with

```
docker-compose kill
docker-compose rm -v
```

I cannot start containers again because I get

```
Cannot start container 0bdb1cfdc4e21c0aaa51a161076e975ed60d2e6d7c66385a870df8b9ab0bac5b: a container has already joined the endpoint
```

When I start a simple container on any host from my cluster and check /etc/hosts I can see that it contains same entries as before killing and removing containers.
Why is it happening is to investigate (it happens sometimes, I haven't found any pattern yet, but I'll try). 
But my question is what can I do in case of not fully removed conteiners from network? Is it possible to do some cleaning manually? Now I can't start my docker-compose containers because it always uses same names for containers and it is conflicting with old names and it makes my cluster pretty unusable...

**Comment by alfredr** [comment]
I've run into this too. The entry for the endpoint is hanging around in consul and this prevents start. It is possible to do cleaning manually -- I found that if you go into consul and delete the corresponding endpoint then you start the container again. 

I wrote this hack to help identify the right keys to delete from consul: https://gist.github.com/alfredr/3d02ecb54fe0a8b6e8dc

**Comment by wouteroosterveld** [comment]
This happened to me as well, I eventually fixed it by restarting my swarm agents. In my case the stale entries were caused by a restart of the docker daemon.

In my setup, I have swarm-agents on all docker hosts in the cluster, and etcd running on one of the hosts, in line with the deployment instructions of shipyard. In my docker.service file, I added "`--cluster-advertise <ip of this host>:2375 --cluster-store etcd://<ip of this host>:4001`" to the docker command. So far so good, until you run apt-get upgrade and the restart of docker daemon on the host that happens to run etcd, takes up a lot of time. It tries to connect to the cluster store that happens to be down because the docker daemon is restarting. Deadlock. Eventually the docker daemon is restarted, but it leaves these stale entries in the overlay network. Recycling the swarm-agents cleaned up the mess for me.

The real fix could be in removing the apparent race condition is the docker daemon restart, in cases where the cluster store is on the docker host that is just restarting. Or possibly by running the cluster-store outside the cluster, which makes sense to me, but I did not test that.

**Comment by fcrisciani** [comment]
Works on master
