### ISSUE TITLE
Endpoint IP Address Assignment

### ISSUE THREAD

**Issue by kingbirdzheng** [docker/libnetwork#665]
I thought Endpoint IP address could either be specified in the Endpoint creation request to the Libnetwork remote drive, or be generated by Libnetwork remote driver if no IP address is specified. For the former case, IP address could be requested from IPAM.

In the IPAM driver description, it seems that IP address is mandatory to create Endpoint and provided by IPAM. In another word, Libnetwork remote driver can have no IPAM function. I believe the interface is not backward-comparability and possibly break some drivers.

Would someone help with clarify it? Thanks.

**Comment by aboch** [comment]
@kingbirdzheng The removal of the address management functions from the network driver (local or remote, no difference) was extensively discussed in and the main reason for #489.

I would not say it introduced a backward compatibility breakage as a docker user would not see a behavior difference even without using the new `docker network cli`.

Also, the remote network driver infrastructure was not available on official non-experimental docker images. The feature is existing experimental now with docker 1.9 release.

Also please be aware it is now possible to instruct docker to use any remote ipam driver instead of the default built-in one, for each docker network.

**Comment by pyakpyak** [comment]
I agree with @kingbirdzheng

In some cases the separation of ipam / remote driver makes things more complicated: You either need to maintain two processes or maintain two apis (which means two driver endpoints) in a single process if your need to share information between two drivers. 

If you could completely disable ipam and keep everything in the remote driver as it was before it would be really nice.

**Comment by kingbirdzheng** [comment]
@aboch do you mean that IP address retrieved from IPAM driver is mandatory. I went through the discussion #489, however I am afraid that I don't get the clear message. 

Based on the interface description of CreateEndpoint in remote driver, it supports both cases as I described.
1) If the CreateEndpoint passes in a IP address (retrieve from IPAM driver), the remote driver will respect the address and use it for the endpoint.
2) If the CreateEndpoint don't pass in any IP address, it's the responsibility of remote driver to provide a IP address.

I agree with you that Libnetwork is on experiment phase, and it has more feasibility to change its behaviors. Unfortunately, based on my observation, several remote drivers (docker-ovs-plugin, Weave network plugin) have been developed based on previous remote driver interface and have IPAM logic in them. I am afraid that they may run into problems with the new IPAM driver.

@pyakpyak 2 plugins is my headache in my case :-)

**Comment by kingbirdzheng** [comment]
@aboch One more question on the IPAM interface. Right now, we have the GetDefaultAddressSpaces interface to retrieve the address space info. In another word, one IPAM driver instance can only have one Address Space. 

Any consideration on support of multiple Address Spaces for one IPAM driver? I believe it's justified requirement to have multiple Address Spaces if we want to have multiple tenants.

**Comment by aboch** [comment]
@kingbirdzheng I understand your concern and others have expressed the same in #489.

Please consider your plugin can can implement both the network driver and the IPAM driver APIs.

Regarding the remote driver documentation, I need to revisit them after the ipam driver introduction. Apologies for that.

The support for multiple address spaces is already in the ipam API. Only thing is that we still kept it out of docker cli for this release. 
The out-of-band address space configuration in the ipam driver is needed only to associate the address space to the datastore. And the `GetDefaultAddressSpaces` function is only needed for libnetwork to decide which address space to use when docker did not pass that info to libnetwork.

**Comment by pyakpyak** [comment]
@aboch i'm also working in rewriting my driver to support ipam and have one question:

I noticed that 'network create' calls `/IpamDriver.RequestPool` and `/IpamDriver.RequestAddress` of my ipam driver. It also seems that libnetwork passed this address as gw parameter for `/NetworkDriver.CreateNetowork`

Why `RequestAddress` is necessary at this point and why the address was passed as the Gw? It looks a little bit strange to me.

**Comment by aboch** [comment]
@pyakpyak 

Yes. For the network being created Libnetwork reserves an address pool with ipam driver and it also reserves a network gateway address.
Then it passes down to the network driver the two allocated entities inside the IPData. 
(Network driver is free to discard the network gateway address if it does not need it)

In most cases though, the network driver will set the sandbox's default gw to the network gateway, as part of the `Join()` call.

If user wants to use a different default gw for the containers, user will pass it as auxiliary-address in the ipam options.

**Comment by pyakpyak** [comment]
@aboch i'm doing L3 routing on the host machine and the ip addresses come from my VPC pool. My routing routes are pretty custom and configured via StaticRoutes. So any assumption about the gw in my case wouldn't work. Even more, i will need to return the address allocated for CreateNetwork back to the pool almost immediately, because otherwise it will be wasted.

Seems much more unneccessary state management . What is the reason making IPAM mandatory?

**Comment by aboch** [comment]
@pyakpyak 
For the reason for introducing ipam driver, please see #489 

If your network driver does not need the allocated network gateway, yes it will be wasted. We felt wasting one IP address per network is a fair compromise, compared to having a common containers' address management infrastructure controlled by libnetwork.

**Comment by pyakpyak** [comment]
@aboch 

I understand the reason why the IPAM was introduced and it definitely provides a convenience when it's necessary. My question was about why we can't delegate everything to a remote driver (as it worked initially) and keep IPAM completely optional. The remote driver api is still the same, so the default ipam could be a noop, rather than something preconfigured.

**Comment by pyakpyak** [comment]
@aboch 

> For the network being created Libnetwork reserves an address pool with ipam driver and it also reserves a network gateway address.

I can see one problem here. When we call `AllocateAddress` there is no way to say if we need a gw address or normal address. These two types should be treated completely differently.

>If user wants to use a different default gw for the containers, user will pass it as auxiliary-address in the ipam options.

Again, the same problem here. If i provide the `--gateway` parameter for my ipam, libnetwork still calls `AllocateAddress` during `CreateNetwork`, but with the provided address as an argument. There is still no way to know from inside the IPAM if we're requesting a gw or just a normal address.

I think in this case it would be less confusing if IPAM will treat gw addresses as first class objects.

Some options:

* Pass a flag to `AllocateAddress` which says if a gw or a normal address is requested.
* Gw could be returned with a separate call. like `GetEndpointGw`
* Gw could be returned along with each allocated address. This approach looks most flexible. In this case you can have full control over your configuration.

**Comment by aboch** [comment]
@pyakpyak 

In current model, ipam driver is just doing address book-keeping for each address pool. Libnetwork instead is the one which knows for which networking entity the address is being requested.

But Ipam API `RequestPool()` actually takes input options and return metadata so that an ipam driver could choose the network gateway and return it as metadata to Libnetwork (see [here](https://github.com/docker/libnetwork/blob/master/network.go#L911)). 
In this case, if no gateway is being passed from cli, libnetwork will not honor the network gateway returned by ipam driver.

The input options and return metadata was added for future extension so that an ipam driver could be potentially backed by a dhcp server.

Going back to today, it looks like #655 is no longer considered a priority for 1.9.0-rc1 (see [comment](https://github.com/docker/libnetwork/pull/658#issuecomment-149377364)).
This should give you some peace of mind regarding your network/ipam driver design ;-)

**Comment by pyakpyak** [comment]
Thanks @aboch 

Let me try that and see if it helps in our use case.

**Comment by kingbirdzheng** [comment]
@aboch thanks for your clarification.

<blockquote>The support for multiple address spaces is already in the ipam API. Only thing is that we still kept it out of docker cli for this release.

<p>The out-of-band address space configuration in the ipam driver is needed only to associate the address space to the datastore. And the GetDefaultAddressSpaces function is only needed for libnetwork to decide which address space to use when docker did not pass that info to libnetwork.</blockquote>

Do you mean that address space can be configured by IPAM remote driver via its own interface although they cannot be configured via docker CLI? If so, how a remote driver interacts with libnetwork's datastore?

One more question is on the NetworkOptionIpam interface.
<code>func NetworkOptionIpam(ipamDriver string, addrSpace string, ipV4 []*IpamConf, ipV6 []*IpamConf) </code>
What's the interaction between this NetworkOptionIpam and IPAM driver?
Shall Libnetwork check whether ipamdriver, addrSpace, ipV4 and ipV6 exists/valid or not?
For one network, what's the purpose on including multiple IPv4 and IPv6 pools?

**Comment by aboch** [comment]
@kingbirdzheng 

Remote ipam driver will have to manage its own datastore, as specified [here](https://github.com/docker/libnetwork/blob/master/docs/ipam.md#datastore-requirements). No assumption are made on the remote driver datastore, if it even exists. (When I said datastore in my previous comment, I meant the remote ipam driver's datastore, having in mind the inbuilt ipam driver.)

Only thing is that libnetwork will send requests to the remote ipam driver with `default local address space` or 'default global address space` for network with local or global scope` respectively (the network scope is derived by the network driver scope, the driver reports during registration).

Ipam driver is free to return the same address space string for both default local and global.

`NetworkOptionIpam()` is the setter function to pass libnetwork the ipam specific configuration for a network. It is needed by libnetwork in order to have all the ingredients when requesting to ipam driver. But the ultimate recipient of this data, the consumer is the ipam driver.

Given most of the fields in the ipam configuration are optional, libnetwork only runs a 
bland validation on this data. It only checks whether the gateway address is valid in case it is passed.

The reason for passing multiple pools is that admin may have a bunch of available IPs fragmented in different subnets. On network create, libnetwork will allocate with ipam each pool and a network gateway each. On endpoint creation it will then allocate an address from the first pool and, if no ips are available, it will request from the next pool and so on.

**Comment by pyakpyak** [comment]
@aboch 

Re #658 and #655. Could you please clarify is the expected behavior here? Is it allowed to return `nil` from `AllocateAddress` now?

Even with the latest master build i'm getting when i return `nil` from my IPAM:
```
sudo ./docker-1.9.0-dev network create --ipam-driver=ipam -d nf nf
Error response from daemon: failed to allocate gateway (): invalid CIDR address:
```

**Comment by aboch** [comment]
@pyakpyak 

The pasted error is coming from [here](https://github.com/docker/libnetwork/blob/master/network.go#L925)

Specifically, `invalid CIDR address:` is coming from the ipam remote package. 
As that part of the code was written with the assumption that in case of a non nil error returned by the remote driver, a valid IP in CIDR form would be present in the response.

**Comment by pyakpyak** [comment]
Thanks @aboch 

Changes from #690 would be really helpful!

Btw, i noticed another thing, which could affect changes which are necessary.

It seems that libnetwork enforces the address returned from `/NetworkDriver.CreateEndpoint` to match  `AllocateAddress` result. Otherwise you get an error:

```
driver modified interface address: endpoint interface IP present (10.0.10.2/32). Cannot be modified with (10.0.10.2/32).; rolled back
```

**Comment by aboch** [comment]
@pyakpyak 

Please take a look at `remote.md` and at the [InterfaceInfo](https://github.com/docker/libnetwork/blob/master/driverapi/driverapi.go#L56) interface.

If your ipam driver implementation returns a non nil address in response to `RequestAddress()`, then libnetwork honors it and does not allow the network driver to overwrite it (even if same address) during the call to `CreateEndpoint()`

**Comment by pyakpyak** [comment]
@aboch got it. thank you for the explanation and quick turnaround with #690. 

A couple of related questions:
* Is `pool` result from `RequestPool` allowed to be a nil value? Currently i'm seeing an error `Error response from daemon: invalid CIDR address` if i return nil.

* In case of nil pools are not allowed: Will libnetwork enforce ip addresses returned by `CreateEndpoint` to be in the pool range or it could be any value?

**Comment by aboch** [comment]
@pyakpyak 

The enforcement on `pool` in `RequestPool` is still there, and I did not want to remove it in #690 because it is really not needed for the scope of the PR.

You can pass any value. Just be aware in case you pass auxiliary addresses
at the docker ux, libnetwork will fail the network creation if any of those addresses does not belong to the pool.

No, the addresses set by the network driver during `CreateEndpoint` are not checked against the pool above.

**Comment by pyakpyak** [comment]
@aboch thanks!

**Comment by kingbirdzheng** [comment]
@aboch 
<blockquote>
NetworkOptionIpam() is the setter function to pass libnetwork the ipam specific configuration for a network. It is needed by libnetwork in order to have all the ingredients when requesting to ipam driver. But the ultimate recipient of this data, the consumer is the ipam driver.
</blockquote>

Since there is no setter interface of IPAM driver api, how can the IPAM driver consume the configuration such as address space, IPv4 pool?

**Comment by mavenugo** [comment]
@kingbirdzheng the IPAM driver configurations are done offline by those who operate the IPAM driver. It need not come from docker UX.

**Comment by kingbirdzheng** [comment]
@mavenugo, do you mean that <code>NetworkOptionIpam()</code> has no impact on IPAM driver? 
Would you please elaborate this option regarding following points when we use it to create a <code>Network</code>?
    1. Will the configuration be passed to IPAM driver?
    2. How it impact the IP address assignment for the <code>Network</code> and <code>Endpoints</code> of the Network?
    3. Shall the Docker user have to synchronize <code>NetworkOptionIpam()</code> with his offline IPAM driver configuration?

Thanks.

**Comment by aboch** [comment]
@kingbirdzheng 

I am not sure why you see a need for a setter interface in IPAM.

If you look at the [ipamapi contract](https://github.com/docker/libnetwork/blob/master/ipamapi/contract.go#L56), and take `RequestPool()` as an example, the client is simply asking ipam driver to allocate (if not allocated yet) the specified pool on the specified address space and return the pool handle (`poolID`).
So that for future requests (allocate/release address, release pool), the client will simply refer to `poolID`.

The only information ipam driver may need to have up front (embedded or out-of-band configured, meaning not via ipamapi.contract interface) is the default address spaces. Because that needs to be reported to libnetwork during ipam driver registration, libnetwork will aks via `GetDefaultAddressSpaces()`

**Comment by aboch** [comment]
@kingbirdzheng 

For most of your questions around `NetworkOptionIpam()` please take  a look at the code, specifically to the function [ipamAllocateversion()](https://github.com/docker/libnetwork/blob/master/network.go#L865)

**Comment by kingbirdzheng** [comment]
@aboch thanks.
