### ISSUE TITLE
Is endpoint ID generated from container Name?

### ISSUE THREAD

**Issue by kingbirdzheng** [docker/libnetwork#808]
#### Description

When I create same name containers down different host(docker daemon), I get the below error response.
<code>
"Error response from daemon: Cannot start container da3fa18d59b44e4706247f596934c92bd138758be0715f04eae1fc2d75225367:  another container is attached to the same network endpoint"
</code>

However, if I create a container with another name, it works.
#### Question

Is endpoint ID generated from container name? Since endpoint is a global resource and I believe container name only have local sense, is there any consideration to connect them?

**Comment by chenchun** [comment]
> Is endpoint ID generated from container name?

Endpoint Id is a random id https://github.com/docker/libnetwork/blob/master/network.go#L704 

> Since endpoint is a global resource and I believe container name only have local sense, is there any consideration to connect them?

Endpoint name generates from container name. https://github.com/docker/docker/blob/master/daemon/container_operations_unix.go#L769-L770
Endpoint names in a network must be distinct since sandboxes in a same network can reach each other using the name of attached endpoints. I assume you are connecting containers to a same overlay network. Overlay network is a multi host networking, therefore you can't connect containers with a same name to the same overlay network.
