### ISSUE TITLE
Wrong content expected by the hook responder

### ISSUE THREAD

**Issue by tonistiigi** [docker/libnetwork#829]
In https://github.com/docker/libnetwork/blob/df3f8a10796e2173732aeafa41af45f970ced9f6/sandbox_externalkey_unix.go#L48 the code is expecting `libcontainer.State` as input but data provided by libcontainer actually has the type `libcontainer/configs.HookState`.

That means that this data doesn't  contain netns path and the `SetKey` should not work.

**Comment by mavenugo** [comment]
@tonistiigi thanks. Is this due to a recent change ? As you might have observed that `processSetKeyReexec` is never invoked in docker 1.10 as libcontainer is still used as library. This function will take effect when it is exercised via the reexec path.

While coding for this in 1.9, I wanted to keep the actual path be owned by docker and not hard-code it in linetwork. Hence was using libcontainer.State which has the required data I was looking for. Hope that make sense. Now if we use configs.HookState, then libnetwork must be hard coded to the path (which isnt bad).

**Comment by tonistiigi** [comment]
@mavenugo I don't think this is recent. The earliest change I could find https://github.com/opencontainers/runc/pull/261 and this uses `HookState` type.

**Comment by mavenugo** [comment]
@tonistiigi ok. but I remember testing for it with `configs.HookState`. Since we didn't have the external binary for runC integrated, I couldn't write a IT for that. Something is a miss here.

BTW, how are you testing this ? Maybe I can check what would have changed.

**Comment by tonistiigi** [comment]
> BTW, how are you testing this ? Maybe I can check what would have changed.

It's used in https://github.com/docker/docker/pull/20662
