### ISSUE TITLE
Question on the semantics of remote network drivers

### ISSUE THREAD

**Issue by bboreham** [docker/libnetwork#904]
My question is about the `Create`/`Delete` and `Join`/`Leave` endpoints. 

I see in #854 you changed your driver to delete the veth in `Leave`. I am puzzled why this is not done in `Delete`.  What is `Delete` supposed to do?

**Comment by mavenugo** [comment]
PTAL https://github.com/docker/libnetwork/pull/905 From a semantics standpoint, I think it is a mistake to do it in `Leave`. But in practice, it really doesn't matter atm. Both the leave and delete are paired today by Docker (Since the concept of publish-service has changed significantly after 1.9). But we are retaining the semantics for future design goals.

**Comment by bboreham** [comment]
Thanks for the update.  Makes it closer to my code :-)
