### ISSUE TITLE
IPVS on libnetwork's overlay

### ISSUE THREAD

**Issue by chanwit** [docker/libnetwork#919]
Hi
I've setup a 3 node cluster with an `overlay` network.
All nodes can ping each other. But when I'm trying to setup LVS for them it's not working as expected.

Here's how I did:

  * Start container `box1` with `--net=multihost`.
  * Start container `box2` with `--net=multihost`.
  * On the master, start container named `ipvs` (with `--previleged` & `--net=multihost`) and try to ping `box1` and `box2`. Everything works fine.
  * Add IPVS table:
```
ipvsadm -A -t 172.18.0.2:80 -s wlc
ipvsadm -a -t 172.18.0.2:80 -r box1:80 -m
ipvsadm -a -t 172.18.0.2:80 -r box2:80 -m
```
  * Double check if the table's added.
```
ipvsadm -L -n
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  172.18.0.2:80 wlc
  -> 10.0.0.2:80                  Masq    1      0          0
  -> 10.0.0.3:80                  Masq    1      0          0
```
  * Try to `curl 10.0.0.2` and `curl 10.0.0.3` (inside container ipvs). Things work perfectly.

  * Then I try to `curl 172.18.0.2` (inside container ipvs) but it's connection timed out.

Do you have any idea what I have missed?

**Comment by chanwit** [comment]
I am guessing this maybe related to  docker/docker#18354?

**Comment by mavenugo** [comment]
@chanwit If you try to access the host mapped port of these backend servers, then yes the fix for docker/docker#18354 will solve it. But since in your case, you are trying to access the backend servers in an `multihost` network from another network `default_gw`, the connectivity will still be prevented by the DOCKER-ISOLATION rule (which is correct and intended by the automatic isolation across docker networks).
If IPVS is not namespace aware, then all of the IPVS related traffic will be subject to the IPTables rules in the host namespace. We have to dig some more to get to the bottom of it.

So, atm, you can try running the IPVS within the same docker network as we dig deeper into the IPVS implementation and its ability to operate across network namespaces.

**Comment by chanwit** [comment]
@mavenugo Thank you for this.
Looking at the kernel, IPVS is namespace aware but haven't check into the source codes yet.

https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/log/net/netfilter/ipvs?id=refs%2Ftags%2Fv4.2-rc6&qt=grep&q=netns

**Comment by luizbafilho** [comment]
Hi @chanwit I did that setup using both Direct Routing and NAT. You have to pay attention in two things, you need to setup the default gateway on that boxes to master's IP, when using the NAT mode, the traffic needs to go to the master.

If you use the Direct Routing, do not forget to add the master IP on the boxes and make sure that this IP will not respond any arp request. 

Here you can get that observations: http://www.ultramonkey.org/papers/lvs_tutorial/html/

**Comment by sanimej** [comment]
@chanwit This is a old issue. Just wanted to clarify what the problem here is.. When using overlay network container is connected to a bridge in a network namespace created specifically for that overlay network. For external connectivity container is also connected to a bridge that is in the default/host network namespace.

With the way you have setup IPVS, pkt will be sent using the overlay network namespace plumbing, but with source address (172.18.0.2 in your case) of the interface that is connected to the default name space bridge. destination host may not have route back to this source ip or would end up getting routed to a wrong destination.

If you want to use IPVS with a overlay network you can set it up using the IP range of the overlay network itself.. for ex:
````
ipvsadm -A -t 10.0.0.100:80 -s rr
ipvsadm -a -t 10.0.0.100:80 -r 10.0.0.2:80 -m -w 1
ipvsadm -a -t 10.0.0.100:80 -r 10.0.0.3:80 -m -w 1
````
10.0.0.2 and 10.0.0.3 are IPs of containers on a different host and 10.0.0.100 is an unused IP in the same overlay subnet.

**Comment by rhim** [comment]
Can someone clarify with an example of what you see in docker service inspect vs. how to use ipvsadm? E.g., in my case, I see the following:
"Endpoint": {
            "Spec": {},
            "Ports": [
                {
                    "Protocol": "tcp",
                    "TargetPort": 8000,
                    "PublishedPort": 8000
                }
            ],
            "VirtualIPs": [
                {
                    "NetworkID": "e7kdg0uh2gkjo8jukyzesf518",
                    "Addr": "10.255.0.2/16"
                },
                {
                    "NetworkID": "3dwxxcxuoo84k0661tqz81o5k",
                    "Addr": "10.0.9.3/24"
                }
            ]
        }
So I assume that 10.0.9.3 and 10.255.0.2 are the VIPs assigned to my service. However, I am unclear on how to use these IPs. E.g., if I curl directly on one of the hosts for 10.0.9.3:8000, it just keeps waiting. 

I don't even have ipvsadm installed on these hosts. Is there any document that details how to use ipvs along with container networking?

I can use the ILB just fine to access the containers backing this service - i.e., I can point curl to any node IP:8000 and it gets RRed to one of the containers. I am more interested in using the VIP of the service.

Thanks in advance,
Himanshu

**Comment by tconrado** [comment]
> @chanwit This is a old issue. Just wanted to clarify what the problem here is.. When using overlay network container is connected to a bridge in a network namespace created specifically for that overlay network. For external connectivity container is also connected to a bridge that is in the default/host network namespace.
> 
> With the way you have setup IPVS, pkt will be sent using the overlay network namespace plumbing, but with source address (172.18.0.2 in your case) of the interface that is connected to the default name space bridge. destination host may not have route back to this source ip or would end up getting routed to a wrong destination.
> 
> If you want to use IPVS with a overlay network you can set it up using the IP range of the overlay network itself.. for ex:
> 
> ```
> ipvsadm -A -t 10.0.0.100:80 -s rr
> ipvsadm -a -t 10.0.0.100:80 -r 10.0.0.2:80 -m -w 1
> ipvsadm -a -t 10.0.0.100:80 -r 10.0.0.3:80 -m -w 1
> ```
> 
> 10.0.0.2 and 10.0.0.3 are IPs of containers on a different host and 10.0.0.100 is an unused IP in the same overlay subnet.

is possible to send the pakt to the 10.0.0.100 from host in this scenario?

**Comment by tconrado** [comment]
I know it is a very old topic, but found a solution for this very well described problem that prevents taking full advantage of the swarm network while routing
[#3532 ](https://github.com/docker/compose/issues/3532#issuecomment-480199364 )
