### ISSUE TITLE
Static routes requested by drivers cause errors if they duplicate other routes

### ISSUE THREAD

**Issue by bboreham** [docker/libnetwork#939]
A driver is allowed to request a `staticRoute` when joining an endpoint. If a container is connected to two Docker Networks, which both request the same route, you get a cryptic error.  Example using the Weave Net driver:

```
$ weave launch # (creates a network called 'weave')
$ docker network create --driver=weavemesh weave2
$ docker run --name=foo -tdi --net=weave alpine /bin/sh
c4a6967fd9e80a32e6c37df6c045c349db7a868fe7e45606de62eba7dbfe9a76
$ docker network connect weave2 foo
Error response from daemon: failed to add interface vethwg89e21 to sandbox: error setting interface "vethwg89e21" routes to ["224.0.0.0/4"]: file exists
```

Since the driver has no context about other routes and no access to the container's network namespace, it cannot avoid this.

Maybe the endpoint priority (if exposed) could be used to pick just one?  Or give the operator a way to pass parameters through to the `JoinEndpoint` call?

(referencing https://github.com/weaveworks/weave/issues/1960)

**Comment by mavenugo** [comment]
@bboreham does `weave lauch` creates the network called `weave` using the `weavemesh` driver ?
In that case, when the container is attached to network weave2, the join call will send the SandboxKey that is same as when it is attached to the first network `weave`. your driver should be able to detect that and avoid adding the route.

But I do see your point about pass more information in `JoinInfo`. Essentially your question is about adding a Get API in this interface to know existing configuration so that the driver could avoid stepping on such container configuration.

**Comment by bboreham** [comment]
I'm just creating two networks with the same driver to illustrate. Imagine they are two different drivers from different vendors.

**Comment by mavenugo** [comment]
@bboreham Yes. What is your opinion on adding a Get API in `JoinInfo` to return the sandbox resources currently managed by libnetwork core across multiple plugins ?
If possible please push a PR so that we can get this moving faster.

**Comment by bboreham** [comment]
@mavenugo there are a couple of problems with this idea:

1. It lets the driver make the decision, not the user.  Maybe the user can arrange things so they connect in an order that achieves the desired effect, but that approach is criticised in https://github.com/docker/docker/issues/20179 .

2. There can be cases where no ordering or driver priority works.  E.g. driver A and driver B both create routes p and q, and the user desires route p from A and route q from B.

3. It requires that only one `JoinEndpoint` is active at a time, otherwise there is a race between fetching the current info and the decision being executed. Is that a restriction you want to bake into the core of Docker?

Right now I am thinking that some UX to let the user specify properties which show up in the `Options` map of `JoinRequest` is a saner approach.

**Comment by mavenugo** [comment]
@bboreham 
docker/docker#20179 is required and we wanted to expose the endpoint priority in 1.10, but couldnt get the UX in on time. By letting the user decide on the priority that will help libnetwork to make sure higher priority plugin wins when there is a contention.

> It lets the driver make the decision, not the user. Maybe the user can arrange things so they connect in an order that achieves the desired effect, but that approach is criticised in docker/docker#20179 .
.
But, by the idea of providing the Get API is to let the plugin know the existing resource so that the plugin could make an informed decision. (For example, if the primary plugin doesnt support multicast, the secondary plugin can still push a 224.0.0.0/24 entry without having to back-off just because it is not the primary plugin.).

Yes, I agree that providing the endpoint priority to the user will be a good starting point.

**Comment by bboreham** [comment]
I'm not clear whether you are advocating an "informed" decision that is sometimes out of date or an interlock so the driver can make its decision knowing nothing will change between `Get` and the action upon its return value. 

The first is a really bad idea in my opinion. The latter just seems unfortunate.

**Comment by bboreham** [comment]
The blog post at https://blog.docker.com/2016/03/docker-networking-design-philosophy/ claims this behaviour as an advantage - "Docker Networking remains the broker to resolve conflicts".

How do I invoke this feature, so that Docker Networking will resolve the conflict?

**Comment by mavenugo** [comment]
@bboreham I think we need the endpoint priority logic and that will help with this functionality. It will also let the user in control over the decision rather than plugins deciding on it.
Would you like to contribute that feature ?
