### ISSUE TITLE
Set Broadcast IP

### ISSUE THREAD

**Issue by tmcmanameyunl** [docker/libnetwork#972]
I would like to set the broadcast ip in a container.  If it's not possible, is this the place to add a request?

**Comment by aboch** [comment]
It is not possible today is because the default builtin IPAM automatically reserves the subnet's network address and the broadcast address.

If you use an IPAM driver (plugin) which implementation does not reserve the broadcast address, then you should be able to assign the broadcast address to your container.

**Comment by jcu006** [comment]
I have propietary software that needs standard broadcast ip (like 172.18.0.255) ¿is there any documentation that explains why broadcast ip 0.0.0.0 is used? ¿why is not possible to change broadcast ip?
